export const GAME = {
  gravity: -30,
  playerMass: 80,
  playerRadius: 0.5,
  eyeHeight: 1.6,
  fixedStep: 1 / 120,
  maxSubsteps: 12,
  airDrag: 0.025,
  terminalVelocity: 90,
  groundFriction: 9,
  groundStopSpeed: 0.35,
  groundMaxSpeed: 14,
  groundAcceleration: 70,
  groundPullFriction: 8,
  airAcceleration: 22,
  airControlSpeed: 28,
  jumpSpeed: 8.5,
  ropeReelSpeed: 9,
  ropeMaxReelSpeed: 18,
  ropeReelAcceleration: 60,
  ropeReelBuffer: 2,
  pullGain: 1.6,
  webRange: 120,
  webFlightSpeed: 160,
  webFlightMinTime: 0.1,
  webZipRange: 85,
  webZipMinPull: 16,
  webZipPullDistance: 34,
  webZipAcceleration: 95,
  webZipMinSpeed: 28,
  webZipPullTime: 1.15,
  webZipStopDistance: 1.2,
  webZipCooldown: 0.85,
  webZipMaxSpeed: 52,
  zipSpeed: 44,
  zipPullDistance: 0.45,
  zipRange: 45,
  zipConeDegrees: 7,
  zipSnapDistance: 2.5,
  zipDualAimDistance: 2.5,
  mountGraceTime: 0.35,
  mountJumpBufferTime: 0.3,
  mountSlingshotSpeed: 24,
  mountSlingshotLift: 8,
  punchSpeed: 3.2,
  wallContactTolerance: 0.03,
  wallRunSpeed: 24,
  wallClimbSpeed: 16,
  wallAcceleration: 90,
  wallBrake: 18,
  wallEntrySpeed: 4,
  wallLookThreshold: 0.25,
  wallAwayThreshold: 0.25,
  wallJumpPush: 9,
  wallJumpLift: 10,
  wallBoostLift: 6,
  wallBoostMaxSpeed: 24,
  wallBoostCooldown: 0.75,
  wallBoostTime: 0.24,
  wallCrestRange: 2.5,
  wallCrestLift: 15,
  wallCrestSpeed: 6,
  wallJumpCooldown: 0.3,
} as const;

export type TravelState =
  | 'Grounded'
  | 'Airborne'
  | 'Firing Web'
  | 'Swinging L'
  | 'Swinging R'
  | 'Swinging Both'
  | 'Zipping'
  | 'WallRunning';
